"""empty message

Revision ID: e350b959409c
Revises: 
Create Date: 2022-09-05 19:22:59.892645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e350b959409c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_prac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='flask_blog'
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_ip', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['flask_blog.auth_prac.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_ip'),
    schema='flask_blog'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices', schema='flask_blog')
    op.drop_table('auth_prac', schema='flask_blog')
    # ### end Alembic commands ###
